version: '2'

services:
  api:
    build:
      context: ./API
    container_name: api_h4g
    ports:
     - "80:5000"
    links:
     - mongo
     - maria
    restart: always

  mongo:
#    image: mongo
    build:
      context: ./mongoDB 
    container_name: mongo_h4g
    volumes:
     - mongo-data:/data/db
    environment:
#      - MONGODB_INITDB_ROOT_USERNAME=root
#      - MONGODB_INITDB_ROOT_PASSWORD=hack4f00d
      - MONGODB_ROOT_PASSWORD=hack4f00d
#    command: mongod
    restart: always  

  maria:
    build:
      context: ./mariaDB 
    container_name: sql_H4G
    restart: always
    volumes:
     - sql-data:/var/lib/mysql

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt_msz
    restart: always
    ports:
     - "8080:1883"
     - "9001:9001"
    volumes:
     - mqtt-data:/mosquitto/data
#     - mqtt-logs:/mosquitto/logs

  avisos:
    build:
      context: ./avisos
    container_name: avisos_msz
    restart: always
    links:
     - api
     - mosquitto
    

volumes:
  mongo-data:
  sql-data:
  mqtt-data:
#  mqtt-logs:
