version: '2'

services:
  api:
    build:
      context: ./API
    container_name: api_h4g
    ports:
     - "80:5000"
    links:
     - mongo
     - maria
    restart: always

  mongo:
#    image: mongo
    build:
      context: ./mongoDB 
    container_name: mongo_h4g
    volumes:
     - mongo-data:/data/db
    environment:
      - MONGODB_ROOT_PASSWORD=hack4f00d
    restart: always  

  maria:
    build:
      context: ./mariaDB 
    container_name: sql_H4G
    restart: always
    volumes:
     - sql-data:/var/lib/mysql

  mosquitto:
    image: ansi/mosquitto
    container_name: MQTT_H4G
    restart: always
    ports:
     - "8080:1883"

volumes:
  mongo-data:
  sql-data:
