version: '2'

services:
  api:
    build:
      context: ./API
    container_name: api_h4g
    ports:
     - "80:5000"
    links:
     - mongo
     - maria
     - rabbit
    restart: always

  mongo:
    image: mongo:latest 
    container_name: mongo_h4g
    volumes:
     - mongo-data:/data/db
    environment:
      - MONGODB_ROOT_PASSWORD=hack4f00d
    restart: always  

  maria:
    build:
      context: ./mariaDB 
    container_name: sql_H4G
    restart: always
    volumes:
     - sql-data:/var/lib/mysql

  rabbit:
    image: rabbitmq:3-management
    container_name: MQTT_H4G
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=hack4f00d
    restart: always
    ports:
     - "15672:15672"
     - "5672:5672"
    volumes:
     - rabbit-data:/etc/rabbitmq


volumes:
  mongo-data:
  sql-data:
  rabbit-data:    
