version: '2'

services:
  API:
    build:
      context: ./API
    container_name: API_H4G
    ports:
     - "80:5000"
    links:
     - mongoDB
     - mariaDB
     - rabbitMQ
    restart: always

  mongoDB:
    image: mongo:latest # custom ?
    container_name: mongo_H4G
    volumes:
     - mongo-data:/data/db
    environment:
      - MONGODB_ROOT_PASSWORD=hack4f00d
      - MONGO_INITDB_ROOT_USERNAME=root
    restart: always  

  mariaDB:
    image: ./mariaDB 
    container_name: sql_H4G
    restart: always
    volumes:
     - sql-data:/var/lib/mysql

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: MQTT_H4G
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=hack4f00d
    restart: always
    ports:
     - "15672:15672"
     - "5672:5672"
    volumes:
     - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"


volumes:
  mongo-data:
  sql-data:
    