maria:
  user: root
  password: hack4f00d
  dbName: MSZ
  dbHostname: maria
  port: 3306
mongo:
  user:
  password:
  dbHostname: mongo
  port: 27017
api:
  hostname: localhost
  port: 80
mqtt:
  hostname: localhost
  port: 8080